<template>
	<div class="tail-bar">
		<div class="left">
			© 2020 - [:now-year:] [:owner:], all rights reserved.
		</div>
		<div class="right">
			Generated by <a target="_blank" href="[:libraryPage:]">[:library:] v[:version:]</a>
		</div>
	</div>
</template>

<script>
export default {
	name: 'TailBar'
}
</script>